name: CI - Node
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
jobs:
  test:
    strategy:
      matrix:
        include:
          - name: Static Tests
            command: bin/static_tests
          - name: Static Lint
            command: bin/static_lint
          - name: Static Pipeline
            command: bin/static_pipeline
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.15.5
          cache: 'npm'
      - name: Install Node dependencies
        run: npm ci
      - name: Run ${{ matrix.name }}
        run: ${{ matrix.command }}
